/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardIndexRouteImport } from './routes/leaderboard/index'
import { Route as QuizListRouteImport } from './routes/quiz/list'
import { Route as QuizCreateIndexRouteImport } from './routes/quiz/create/index'
import { Route as QuizQuizIdIndexRouteImport } from './routes/quiz/$quizId/index'

const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardIndexRoute = LeaderboardIndexRouteImport.update({
  id: '/leaderboard/',
  path: '/leaderboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizListRoute = QuizListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => QuizRoute,
} as any)
const QuizCreateIndexRoute = QuizCreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => QuizRoute,
} as any)
const QuizQuizIdIndexRoute = QuizQuizIdIndexRouteImport.update({
  id: '/$quizId/',
  path: '/$quizId/',
  getParentRoute: () => QuizRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/quiz': typeof QuizRouteWithChildren
  '/quiz/list': typeof QuizListRoute
  '/leaderboard/': typeof LeaderboardIndexRoute
  '/quiz/$quizId/': typeof QuizQuizIdIndexRoute
  '/quiz/create/': typeof QuizCreateIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/quiz': typeof QuizRouteWithChildren
  '/quiz/list': typeof QuizListRoute
  '/leaderboard': typeof LeaderboardIndexRoute
  '/quiz/$quizId': typeof QuizQuizIdIndexRoute
  '/quiz/create': typeof QuizCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login': typeof LoginRoute
  '/quiz': typeof QuizRouteWithChildren
  '/quiz/list': typeof QuizListRoute
  '/leaderboard/': typeof LeaderboardIndexRoute
  '/quiz/$quizId/': typeof QuizQuizIdIndexRoute
  '/quiz/create/': typeof QuizCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/quiz'
    | '/quiz/list'
    | '/leaderboard/'
    | '/quiz/$quizId/'
    | '/quiz/create/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/quiz'
    | '/quiz/list'
    | '/leaderboard'
    | '/quiz/$quizId'
    | '/quiz/create'
  id:
    | '__root__'
    | '/login'
    | '/quiz'
    | '/quiz/list'
    | '/leaderboard/'
    | '/quiz/$quizId/'
    | '/quiz/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  QuizRoute: typeof QuizRouteWithChildren
  LeaderboardIndexRoute: typeof LeaderboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard/': {
      id: '/leaderboard/'
      path: '/leaderboard'
      fullPath: '/leaderboard/'
      preLoaderRoute: typeof LeaderboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/list': {
      id: '/quiz/list'
      path: '/list'
      fullPath: '/quiz/list'
      preLoaderRoute: typeof QuizListRouteImport
      parentRoute: typeof QuizRoute
    }
    '/quiz/create/': {
      id: '/quiz/create/'
      path: '/create'
      fullPath: '/quiz/create/'
      preLoaderRoute: typeof QuizCreateIndexRouteImport
      parentRoute: typeof QuizRoute
    }
    '/quiz/$quizId/': {
      id: '/quiz/$quizId/'
      path: '/$quizId'
      fullPath: '/quiz/$quizId/'
      preLoaderRoute: typeof QuizQuizIdIndexRouteImport
      parentRoute: typeof QuizRoute
    }
  }
}

interface QuizRouteChildren {
  QuizListRoute: typeof QuizListRoute
  QuizQuizIdIndexRoute: typeof QuizQuizIdIndexRoute
  QuizCreateIndexRoute: typeof QuizCreateIndexRoute
}

const QuizRouteChildren: QuizRouteChildren = {
  QuizListRoute: QuizListRoute,
  QuizQuizIdIndexRoute: QuizQuizIdIndexRoute,
  QuizCreateIndexRoute: QuizCreateIndexRoute,
}

const QuizRouteWithChildren = QuizRoute._addFileChildren(QuizRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  QuizRoute: QuizRouteWithChildren,
  LeaderboardIndexRoute: LeaderboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
